### PR TITLE
Fixing some flow types on index.js on isPackageInstalled function

### PR DESCRIPTION
**Pull request by MateusAndrade**
# Overview

Fixing some flowTypes on isPackageInstalled function promise and packageName param.

# Test Plan
Clone the PR, and call the isPackageInstalled function.

### CODE REVIEW

**Comment by mikehardy** [comment]
Hi there! Fixing types is awesome, but it's hard for me to say just by looking whether this is valid or not. I mean, developer to developer, this looks obvious - but what if my mind is playing tricks on me?

Could you add a flow check package.json run script (handy example: https://github.com/react-native-community/react-native-device-info/blob/master/package.json#L13) to make sure the result is good, and if it looks like there's a good place to wedget it in the circle CI config make sure it is called there? Somewhere around here https://github.com/react-native-community/react-native-share/blob/master/circle.yml#L18 should work I think - with the flow-bin being a new devDependency as needed I think...

Most importantly (vs the obvious change here) it should make sure it doesn't regress in the future

**Comment by MateusAndrade** [comment]
@mikehardy sure! I just got a doubt, or even a suggestion: is there any contrib guide or something like that? Because i got stuck trying to commit my changes with commitlint. And i dont found any doc explaining how should i commit, etc.

**Comment by mikehardy** [comment]
Alas, there is not. I remember attempting to send a patch to this library was in fact the first time that I was confronted by my total lack of knowledge of all of react-native (with husky, commitlint, changelog formats, etc etc etc). I'm not sure I'd be qualified to write it either but I know @jgcmarins has recently added some documentation (issue templates etc) and he may have set up the package.json originally - maybe he knows?

**Comment by jgcmarins** [comment]
Awesome discussion!
There are few rules here: https://github.com/react-native-community/react-native-share/blob/44ac820e77bc90f331490320a509a52d630272b2/commitlint.config.js
And there is missing a contributing guide explaining how commit lint works.

**Comment by MateusAndrade** [comment]
@jgcmarins would be really amazing if someone write a guide about commit lint, because i needed to use --no-verify to skip the lint process as there is any example about this

**Comment by jgcmarins** [comment]
here you go: https://github.com/react-native-community/react-native-share/issues/477
let's work on this

**Comment by mikehardy** [comment]
I like that this was merged - but I was hoping for the flow check in CI prior to make sure it is good and doesn't regress later. I did not test it locally

**Comment by jgcmarins** [comment]
Agreed, we can add the flow check step on another PR

**Comment by MateusAndrade** [comment]
@mikehardy  i agree with that. I will look at the CI/Flow Check on this weekend =D

**Comment by MateusAndrade** [comment]
#480

**Pull request merged**
