### PR TITLE
Reverting #505 to bring sharing to insta stories back

### LINKED ISSUE #556: Instagram Stories on v2
## Ask your Question

Is instagram stories working on this version?

### PR DESCRIPTION
**Pull request by hbarylskyi**
# Overview
Trying to bring the Instagram Stories feature back. Hopefully resolves #556 

So I've reverted #505. After that, I got this error: 
```
Undefined symbols for architecture x86_64:
  "_RCTSetLogFunction", referenced from:
      -[exampleTests testRendersWelcomeScreen] in exampleTests.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I was tweaking Xcode settings and seems like disabling Dead Code Stripping on `example` project fixed the error. Disabling it on RNShare did not help. 
Also:
* added photo usage description in `example` and added `instagram` & `instagram-stories` to query schemes in Info.plist. 
* added `*.js` to `dev-sync` script so that js files would be copied over to `node_modules` of `example`.
* webstorm applied some styling changes according to .eslintrc.
* added a 'Share to IG Story' button in `example` to test the feature.

# Test Plan
1. Install on device
2. Tap the 'Share to IG Story' button
3. If Instagram is installed - it will be opened with the Stories screen. If it's not installed - you will be taken to the appstore.

As to my knowledge, feature was not implemented on Android.

### CODE REVIEW

**Comment by vforvasile** [comment]
I tested this on RN 61.5 with a local file and it works.  I found out that promise is not getting resolved after Instagram dialog appears, this could be an issue if you're relying on response to cancel some other actions.

**Comment by jgcmarins** [comment]
@vforvasile thanks a lot for testing this!
@hbarylskyi any chances to update branch with master?
Thanks everyone!

**Comment by hbarylskyi** [comment]
@jgcmarins hey, I’ll try to update the branch during next week. Have a lot of work atm.

**Comment by MateusAndrade** [comment]
> @jgcmarins hey, I’ll try to update the branch during next week. Have a lot of work atm.

Thanks!!! There is anything that we can do for help you? Maybe giving access to @jgcmarins or me to update your base branch?

**Comment by hbarylskyi** [comment]
Hey guys, I've merged master in my branch. Also I've added you both as collaborators on my repository.  @MateusAndrade @jgcmarins

**Comment by MateusAndrade** [comment]
Thanks @hbarylskyi !! Did you tested a release build on iOS?

**Comment by Rizaldinurm** [comment]
How can I help to finish this pull request ?

**Comment by hbarylskyi** [comment]
@MateusAndrade nope, didn’t test it.

**Comment by MateusAndrade** [comment]
> How can I help to finish this pull request ?

Testing this with a release build on IOS would be help a lot. After merging #449 there was some errors when a iOS release build was triggered.

**Comment by beardwin** [comment]
Hey all. I'm interested in using this lib on a project I'm working on which requires sharing to IG stories. In an attempt to see where this PR is at, and to perhaps help test, I cloned @hbarylskyi's branch. I've also never worked on an RN lib before, so I might be doing this wrong, but I did the following post clone:

1. cd into `example`
2. `yarn`
3. cd into `example/iOS` and do a `pod install`
4. cd back into the root and do a `yarn` then `yarn dev-sync`
5. cd back into `example` and do a `react-native run-ios`

Everything builds fine and installs to the simulator, and launches. However, at that point I get a runtime error with `@react-native-community/react-native-device-info: NativeModule.RNDeviceInfo is null`. If I add it and `pod install` then that error goes away (only to be replaced with a similar error regarding Bugsnag). I tried finding where the device info and Bugsnag dependencies were coming from but came up short.

Any guidance here? Perhaps I've misunderstood some of the setup instructions from [here](https://github.com/react-native-community/react-native-share/issues/556#issuecomment-536597328), or I've piecemealed some things together inappropriately.

Thanks!

**Comment by beardwin** [comment]
hey all - 

just an FYI that I cloned @hbarylskyi's repo, setup the example project (just `yarn`, `pod install`, `yarn dev-sync`, etc), and then installed and tested on my device (iPhone XS w/ iOS 13.3) via `react-native run-ios --device "My Device" --configuration Release` and it worked great. I was able to post a story to my IG without any issue.

**Comment by MateusAndrade** [comment]
> just an FYI that I cloned @hbarylskyi's repo, setup the example project (just `yarn`, `pod install`, `yarn dev-sync`, etc), and then installed and tested on my device (iPhone XS w/ iOS 13.3) via `react-native run-ios --device "My Device" --configuration Release` and it worked great. I was able to post a story to my IG without any issue.

Thankns @beardwin !!!!!! 🎉🎉🎉🎉🎉

**Comment by beardwin** [comment]
my pleasure! Would be nice if another person could validate what I experienced. I just started peaking at this project today so I'm missing a lot of context.

**Comment by MateusAndrade** [comment]
> my pleasure! Would be nice if another person could validate what I experienced. I just started peeking at this project today so I'm missing a lot of context.

I think we are good to go on that, there is been a long time since this PR is open, and we got a lot of changes during this process. Merging this on the `master` can be a way to let more people test that. :Btw, let us know if you found anything that affects your project with the last version. 😄

**Comment by friederbluemle** [comment]
Thanks for merging @MateusAndrade - Quick follow-up PR here: #674

**Pull request merged**
