### PR TITLE
Fix twitter fallback text

### PR DESCRIPTION
**Pull request by RalfNieuwenhuizen**
Change "message" parameter to "text": https://dev.twitter.com/web/tweet-button/web-intent

### CODE REVIEW

**Comment by b1acKr0se** [comment]
It's been 6 months since this pull request was open and no one willing to merge this?

**Comment by jgcmarins** [comment]
It's already fixed on Android: https://github.com/react-native-community/react-native-share/blob/master/android/src/main/java/cl/json/social/TwitterShare.java#L14

**Comment by b1acKr0se** [comment]
@jgcmarins Thanks. Just a quick question: When should I expect these changes to take effect on npm?

**Comment by jgcmarins** [comment]
@b1acKr0se good point.
We're working on stable version.
Checklist for next release:
- [ ] Add tests
- [ ] Add a full example that ensures at least happy path

**Pull request merged**
