### PR TITLE
Improve tests and simplify example setup

### PR DESCRIPTION
**Pull request by charpeni**
# Overview

This pull request aims to prevent any flow errors that could impact consumers of this library.

## Example App changes

The example app was accessing `react-native-share` through `node_modules` and from `git+https://git@github.com/react-native-community/react-native-share.git`.

This means that we can't test the example folder with local changes and that our example app will always fetch `react-native-share` from yarn cache, not necessarily master.

Instead of this setup, I configure the example app's metro config to reach `react-native-share` from `../`. 

[For further information on the setup.](https://medium.com/@charpeni/setting-up-an-example-app-for-your-react-native-library-d940c5cf31e4)

## CircleCI changes

To catch these flow errors that could be triggered while using the lib, we can run a flow check within the example folder. So, from now, flow will be run in the example folder in CircleCI.

# Test Plan

CircleCI & ran the example app on iOS & Android.

### CODE REVIEW

**Comment by charpeni** [comment]
Remaining flow errors will be fixed in #538.

**Comment by MateusAndrade** [comment]
This looks REALLY GOOD. Did you tested this changes on a device/simulator? I was trying something similar and ended using the file-sync approach.

Btw, thanks for your help. :D

**Comment by charpeni** [comment]
> I see that the CI is failing on the example app, on something related to flow. You can give a look at that?

Yes, it will be fixed by #538.

**Comment by MateusAndrade** [comment]
> > I see that the CI is failing on the example app, on something related to flow. You can give a look at that?
> 
> Yes, it will be fixed by #538.

Im going to give a look at #538 tomorrow. You can talk with @maryjenel to apply the suggestions?

**Comment by MateusAndrade** [comment]
@charpeni you can update your branch with the last changes on master?

**Comment by charpeni** [comment]
Done, tests are green.

**Comment by jgcmarins** [comment]
Awesome \o/

**Comment by charpeni** [comment]
Thank y'all for maintaining this package!

**Pull request merged**
