### PR TITLE
Added instagram and snapchat for Android

### PR DESCRIPTION
**Pull request by priyankinfinnov**
Added instagram and snapchat for Android for [https://github.com/EstebanFuentealba/react-native-share/issues/216](this issue).
iOS is not done though.

### CODE REVIEW

**Comment by priyankinfinnov** [comment]
Hey @EstebanFuentealba, can you please check and accept this?

**Comment by jgcmarins** [comment]
@priyankinfinnov could you solve conflicts, please?

**Comment by nicholasess** [comment]
@priyankinfinnov the conflicts persist

**Comment by jgcmarins** [comment]
@priyankinfinnov looks good!
could you please resolve conflicts?

**Pull request closed without merging**
