### PR TITLE
Update react-native to 0.61.4

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates the `react-native` dependency of the example project to the latest version `0.61.4` including all project support files.

In a separate commit, it fixes a few ESLint errors and warning. There is also an individual commit that adds `node_modules` to the `[untyped]` section in `.flowconfig`. This was an **existing** setting, but since it's the _only_ difference to a vanilla `.flowconfig` from the default RN template, I kept it separate for easy revertability.

Successfully verified and tested on:
- Android Device (Xiaomi Mi A2)
- Android Emulator (Pixel 3a)
- iOS Device (iPhone 8)
- iOS Simulator (iPhone X)

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the PR head branch. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest base branch. If it isn't, or if you want me to change anything, please let me know, and I will update the branch as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by friederbluemle** [comment]
Thanks for reviewing @MateusAndrade - Just a gentle reminder to use a _regular_ merge (no squash) for this PR, so we can easily `git revert` the commit that customized `.flowconfig` (once the existing errors are resolved in a different PR).

**Comment by friederbluemle** [comment]
As always, good question @mikehardy 

Rebase and/or squash merges on GitHub can be a good option in the following scenarios:

- The PR head branch contains multiple commits that logically make no sense in having as separate commits on the base branch (a good example are "fixup" commits)
- The PR head branch is out-of-date with the base branch (which would create a tangled spaghetti Git commit graph)
- The PR contains merge commits (for example after using the dreaded "Update branch" button, which _merges_ the base branch into the PR branch)

If one or more of these conditions are met, _and_ the PR author is unavailable or unresponsive in requests to update/change the PR branch, then a GitHub squash/rebase merge may be the preferred way of merging a PR.

Otherwise, if the pull request contains only a single commit (or cleanly structured commits), **and** is _already fully rebased_, there is not really any benefit in using a rebase or squash merge on GitHub. All it does is rewrite the commit(s) on the GitHub server, which (as you mentioned) effectively removes any signatures from the commits and changes the committer IDs/dates.

In the case of rebase merges, it will also make it _impossible_ to identify the commits that went into the base branch through a particular PR (it would just be one straight line, without a reference to the PR number). For squash merges at least, GitHub would append the PR number to the end of the modified Git commit message. Additionally, in both cases the PR author would have to _force delete_ their local branch using `git branch -D` (Git does not see it as merged), potentially after manually having to verify that all changes made it into the base branch. With a regular merge, "graceful" branch deletion (`git branch -d`) can be used, with which Git _guarantees_ that no information will be lost.

**Comment by mikehardy** [comment]
Thanks for the detailed explanation @friederbluemle - all makes sense. I will say that in practice the rebase merge (not squash) has worked well for years on AnkiDroid and makes for a squeaky clean master timeline without a lot of PR rebasing which is nice, but I can see the benefits of merge as well. Good to think through as a maintainer either way

Sorry react-native-share people for chatting up the PR thread :)

**Comment by friederbluemle** [comment]
Thanks for merging. Since the commits were squashed, there's no single commit on the default branch that can easily be reverted once the type errors have been fixed. I'll keep the ref as a separate branch on my fork, so the customization to `.flowconfig` can be fetched from there and reverted if needed:

### Step 1

Fix type errors and commit changes

### Step 2

```
git fetch https://github.com/friederbluemle/react-native-share.git flowconfig
git revert FETCH_HEAD
```

### Step 3

Ensure that `yarn flow` in `example/` still passes.

**Pull request merged**
