### PR TITLE
Android not installed feedback

### PR DESCRIPTION
**Pull request by RalfNieuwenhuizen**
Requires https://github.com/EstebanFuentealba/react-native-share/pull/220

### CODE REVIEW

**Comment by priyankinfinnov** [comment]
@EstebanFuentealba please can you review this and merge.

**Comment by jgcmarins** [comment]
@RalfNieuwenhuizen looks good!
could you please resolve conflicts?

**Comment by RalfNieuwenhuizen** [comment]
@jgcmarins I tried but something is broken in the eslint for the example app. I cannot commit.

**Comment by jgcmarins** [comment]
@RalfNieuwenhuizen what error?
Could you provide stack trace?

**Comment by RalfNieuwenhuizen** [comment]
```
$ git commit
 ❯ Running tasks for *.js
   ✔ yarn prettier
   ✖ eslint --fix
     git add
✖ "eslint --fix" found some errors. Please fix them and try committing again.

/Users/user/react-native-share/example/App.js
 9:19  error  Unable to resolve path to module 'react-native-share'  import/no-unresolved
12:7   error  'instructions' is assigned a value but never used      no-unused-vars
58:3   error  Unused style detected: styles.instructions             react-native/no-unused-styles

✖ 3 problems (3 errors, 0 warnings)

pre-commit:
pre-commit: We've failed to pass the specified git pre-commit hooks as the `lint:staged`
pre-commit: hook returned an exit code (1). If you're feeling adventurous you can
pre-commit: skip the git pre-commit hooks by adding the following flags to your commit:
pre-commit:
pre-commit:   git commit -n (or --no-verify)
pre-commit:
pre-commit: This is ill-advised since the commit is broken.
pre-commit:
```

**Comment by jgcmarins** [comment]
I think for this case you can use `-n` on commit.
We need to improve this later on, we should use lint separately.

**Comment by RalfNieuwenhuizen** [comment]
@jgcmarins in that case, pushed!

**Pull request closed without merging**
