### PR TITLE
Fix broken link to WhatsApp in the iTunes store.

### PR DESCRIPTION
**Pull request by scovetta**
The original link isn't resolving, so changed to a non-locale-specific iTunes URL.

While I was there, changed HTTP -> HTTPS.

### CODE REVIEW

**Comment by sibelius** [comment]
is this a problem in android as well?

**Comment by scovetta** [comment]
@sibelius I think Android is fine -- the only [reference](https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/social/WhatsAppShare.java#L14) I can find is to `market://details?id=com.whatsapp`, which looks correct as per [this doc](https://developer.android.com/distribute/marketing-tools/linking-to-google-play.html#android-app).

**Comment by jgcmarins** [comment]
@sibelius can we merge this?
thanks to @wasedaigo and @scovetta

**Comment by nicholasess** [comment]
@sibelius Do you found someone problem with the PR?

**Pull request merged**
