### PR TITLE
Share with Files app

### PR DESCRIPTION
**Pull request by gevorg94**
# [iOS] Share with Files app.
Open only the `Files` app to share URLs.
Requires ios 11+ and won't affect older versions in case of use
Supports only URLs

add `saveToFiles: true` to the options.

```
Share.open({
    type: 'application/pdf',
    urls: [PATH_TO_FILE],
    saveToFiles: true,
});

```
Will throw an error when the picker is canceled by a user.

### CODE REVIEW

**Comment by gevorg94** [comment]
example_preview

**Comment by MateusAndrade** [comment]
Hey @gevorg94 , this looks really good! What do you think about setting a example of using that the example app? 😄

**Comment by gevorg94** [comment]
Thanks @MateusAndrade . I've added an example of usage.

In case to test the example before merging this PR please replace
`"react-native-share": "git+https://github.com/react-native-community/react-native-share.git",`
with
`"react-native-share": "git+https://github.com/gevorg94/react-native-share.git#share-files-app",` in package.json

and in App.js replace
`const pdfUrl = 'https://raw.githubusercontent.com/react-native-community/react-native-share/master/assets/dummy.pdf';`
with
`const pdfUrl = 'https://raw.githubusercontent.com/gevorg94/react-native-share/share-files-app/assets/dummy.pdf';`
(line 140).

I've also linked rn-fetch-blob to download and store files locally. It will allow to share files with the `Files` app.

**Comment by MateusAndrade** [comment]
Hey @gevorg94 you can update your base branch? I changed some configs at the CI, and i think we will need your base with the the latest config to run the checks properly and merge this.

Thanks!

**Comment by gevorg94** [comment]
@MateusAndrade  Done!

thank you too.

**Comment by MateusAndrade** [comment]
> thank you too.

I see that you add `rn-fetch-blob`to test this change. Btw, we should update the example app on Android to build without any problem. The CI is failing, possible due to a link error or something similar to that.

**Comment by gevorg94** [comment]
Hey @MateusAndrade 
I've removed `rn-fetch-blob` and added functionality to share base64 files as well.

Now you can call
```
Share.open({
    type: 'application/pdf',
    urls: [PATH_TO_FILE, 'data:application/pdf;base64,...'], // base64 string or path to the file
    saveToFiles: true,
});
```
to share with the `Files` app.

All Android changes have been reverted but the CI is failing again.

**Comment by MateusAndrade** [comment]
Hey @gevorg94 , sorry for the late answer. Recently i tested some changes on the CI that can be related to that. Btw, we can fix that with another PR.  I will merge that, and send a fix on the example App. 😄

**Comment by friederbluemle** [comment]
@MateusAndrade - Please check #690 - It _should_ fix the CI, and you can try again.

**Comment by MateusAndrade** [comment]
> @MateusAndrade - Please check #690 - It _should_ fix the CI, and you can try again.

I think we can set that at the circle CI, i was looking at some project that have this setup. Btw, i will merge your PR and see if this PR runs fine.

**Comment by friederbluemle** [comment]
> > @MateusAndrade - Please check #690 - It _should_ fix the CI, and you can try again.
> 
> I think we can set that at the circle CI, i was looking at some project that have this setup. Btw, i will merge your PR and see if this PR runs fine.

Sounds good! If you find a way to set this on Circle CI please let me know, and we can revert my PR. I'm also interested in how to fix this _without_ modifying the metro config.

**Comment by MateusAndrade** [comment]
> Sounds good! If you find a way to set this on Circle CI please let me know, and we can revert my PR. I'm also interested in how to fix this _without_ modifying the metro config.

Sure! Just merged #690, let's see if the CI now runs properly. After that we can look on reverting this. 🎉

**Comment by MateusAndrade** [comment]
It looks like we are done @gevorg94, @friederbluemle ! 😮 😮 😮  Thanks for the help!

**Comment by gevorg94** [comment]
Thank you too! @MateusAndrade

**Comment by sleep9** [comment]
This works but has a conflict with @react-navigation/drawer. Causing the drawer to glitch out after sharing.

**Pull request merged**
