### PR TITLE
Implemented succeed and failed test 

### PR DESCRIPTION
**Pull request by indapublic**
Implemented two tests (one succeed and one failed) for bug illustrating which described in issue #407

### CODE REVIEW

**Comment by mikehardy** [comment]
In general - *always* better to rebase from master instead of merge - the merge commits make it very difficult to review the changes by themselves

**Comment by indapublic** [comment]
@mikehardy Force push (after rebase) will close PR

**Comment by mikehardy** [comment]
I'm afraid I don't understand, sorry. When I work on PRs that for some reason or another are long-lived, I typically have a remote called "upstream" for the main repo, and I do `git fetch upstream && git rebase upstream/master && git push origin +branchname` and everything's fine? Occasionally ther eare conflicts in the rebase to work through but that's usually not bad. This does not close the PR, a force-push is simply noted in the github UI and the commit history is re-written.

Here's an example - search for force-push here and you'll see there have been 5 so far, and if I can successfully find time to respond to the latest comments, there'll be another shortly.. https://github.com/ankidroid/Anki-Android/pull/5151

**Comment by MateusAndrade** [comment]
> I'm afraid I don't understand, sorry. When I work on PRs that for some reason or another are long-lived, I typically have a remote called "upstream" for the main repo, and I do `git fetch upstream && git rebase upstream/master && git push origin +branchname` and everything's fine? Occasionally ther eare conflicts in the rebase to work through but that's usually not bad. This does not close the PR, a force-push is simply noted in the github UI and the commit history is re-written.
> 
> Here's an example - search for force-push here and you'll see there have been 5 so far, and if I can successfully find time to respond to the latest comments, there'll be another shortly.. [ankidroid/Anki-Android#5151](https://github.com/ankidroid/Anki-Android/pull/5151)

Dealing with rebase, merge, etc can be painful. I got some issues with this today. You can share any article to help with that?

**Comment by mikehardy** [comment]
Hmm - unfortunately I do not have articles. I always had to google it when I learned, but more than anything it was just repetition. I agree it can be painful, but especially when there are no conflicts, it is effortless at least. When there are conflicts I just follow the command line very very carefully - the "git status" output always tells you what to do, including which file has the conflict, what command to run to clear it when you are done, what command to run after. So in general. And worse case (as the git status command will tell you) you can always `git rebase --abort` if things went to ____, and just try again clean. So for me when there is a conflict, it's usually a `git status`, (it tells you which files are conflicted) so I open them in an editor and search for `>>>` to start fixing. Then another `git status` and it tells you to `git add yourconflictedfile`, then `git status` again, and it tells you to `git rebase --continue` where it moves to the next patch. Repeat that same pattern using `git status` to guide you through

**Comment by indapublic** [comment]
@mikehardy You should force push to existing branch after rebase, isn't it?

**Comment by indapublic** [comment]
Hm, OK, i was wrong, @mikehardy. I'm was sure that PR should be closed after force pushing. Probably I met those behaviour earlier somewhere. Thanks

**Comment by mikehardy** [comment]
@indapublic yes! what you've done, if you think of git commit history as a stack, is temporarily popped your commit(s) off the stack and put them aside. Then you take whatever commits were missing from the branch you rebased onto and pushed them on to your stack, then re-pushed your commits back on top at the end. So now your history is different from the upstream in an incompatible way, and force-push is the only way. There are some projects that do not like this workflow style because rewriting history is considered bad. I agree for master, but for PRs? A clean (after force-pushing) history is a beautiful thing to me. Hope all of this was at least informative and useful for the future :-). Cheers

**Comment by mikehardy** [comment]
This PR now, for instance, is now super easy to understand, a thing of beauty :-). Thanks

**Comment by MateusAndrade** [comment]
I would like to give a deep look at this PR, but doing a overview LGTM. 😁

**Comment by indapublic** [comment]
@mikehardy Seems like all commits require sign but I don't use it. Could you merge it without that?

**Comment by mikehardy** [comment]
Oh - I don't know about that signing. I personally try to sign things (occasionally a use a computer without my GPG stuff installed) but I didn't know it was a requirement. I suppose that is project dependent. None of the other projects I work on have it as a requirement, so it isn't a github-general thing, but maybe this project requires it? I don't know. I personally wouldn't care but I just try to help I don't want to be a policy maker here as I have too many other things going on

**Comment by indapublic** [comment]
Screenshot 2019-05-14 at 13 37 13

Looks like project requirement. And yes, I never met this before on github

**Comment by mikehardy** [comment]
Huh - I do have admin rights in the repo though I have not exercised them. For me I see the various merge options are allowed, so it looks like an admin choice. I don't think it's a hard block here, just an admin choice. In the meantime it isn't a bad thing to set up signing for the future either way

**Comment by indapublic** [comment]
It's not bad, agreed, but I don't have any GPG stuff and time to configure it. @jgcmarins, could you help me with merging?

**Comment by MateusAndrade** [comment]
@jgcmarins you think we are ready for a release? =D

**Comment by MateusAndrade** [comment]
> Sure, can someone help me with release notes?

Site! I can give a look at this later. We just need to pick the commits and describe the changes?

**Pull request merged**
