### PR TITLE
Add support for Instagram sharing

### PR DESCRIPTION
**Pull request by RalfNieuwenhuizen**

### CODE REVIEW

**Comment by donnes** [comment]
@RalfNieuwenhuizen In your fork, the method `shareSingle` works with Instagram to post a photo?

**Comment by oferRounds** [comment]
@EstebanFuentealba @jgcmarins any chance this could be merged?

**Comment by MarkOSullivan94** [comment]
@RalfNieuwenhuizen you got any preview screenshots / gifs we could see for this?

**Comment by RalfNieuwenhuizen** [comment]
@MarkOSullivan94 https://www.dropbox.com/s/w3y95uy806rwo47/SVID_20180425_154749.mp4?dl=0

**Comment by jgcmarins** [comment]
Thanks @RalfNieuwenhuizen

**Pull request merged**
