### PR TITLE
feature/updating example version

### PR DESCRIPTION
**Pull request by MateusAndrade**
# Overview
Updating dependencies of the project to newer versions.  The newer versions of the example are now:

```json
{
  "name": "react-native-share-example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "react": "16.8.3",
    "react-native": "0.59.5",
    "react-native-share": "git+https://github.com/react-native-community/react-native-share.git"
  },
  "devDependencies": {
    "@babel/core": "^7.4.3",
    "@babel/runtime": "^7.4.3",
    "babel-jest": "^24.7.1",
    "jest": "^24.7.1",
    "metro-react-native-babel-preset": "^0.53.1",
    "react-test-renderer": "16.8.3"
  },
  "jest": {
    "preset": "react-native"
  }
}

```

Please note that this was tested on a XT1078(23) and on a emulator running a Nexus(28). On both cases, calling all the library options have running without problem. 

Unfortunately, i cant test this example on IOS. This PR can only be merged if someones run this demo on a IOS without any problem.

# Test Plan
There a few steps that need to be validate to ensure that this update is working.  I already tested and validated the project in Android, pending the validation in IOS and CI. To facilitate, if you can try one of the options without problems, please inform in the comments. =D

Also i used this rn-diff to update the project: https://github.com/react-native-community/rn-diff-purge/compare/release/0.55.4..release/0.59.5 .

Unfortunately, due to MANY binary errors in IOS. I had to redo the application from scratch by adding the features that were already present in the example.

# Pending Tests

* [x]  Run project on IOS
* [x]  Test share options without any problem
* [x]  Run project on Android
* [x]  Test share options without any problem
* [x]  Update PR explaining about making the app from scratch again

### CODE REVIEW

**Comment by MateusAndrade** [comment]
@mikehardy this would be REALLY good. Im having some trouble updating the ios binaries, o think make a fresh project with the existing code would be easier. By doing this, i can see your sugestion

**Comment by mikehardy** [comment]
Yeah, I do just about everything to avoid touching xcode files :-). Pods is one step, recreating examples with the script I made and linked above is another, and I'm about to start using "xcake" if I can manage it. There are few things worse than dealing with XCode project file breakage...

**Comment by MateusAndrade** [comment]
@mikehardy  Xmake looks interesting, but i think for react-native cocoapods are good enough. Did you tried xmake on any rn project?

**Comment by mikehardy** [comment]
@MateusAndrade I have not - I just have dreams after integrating Fastlane with match while using cocoapods and seeing how sane iOS development *can* be. But I haven't had my project file explode in months so no urgent desire at the moment

**Comment by MateusAndrade** [comment]
@mikehardy  i created a new project from scratch and rewrited the existing examples again. Since the idea of a example is being simple, i removed flow types, and other things trying to let the code easy to understand

**Comment by mikehardy** [comment]
Interesting about the package install message that does seem odd
The update looks nice though, good to have it running on current

Not good about the link though - if there is any problem at all in link that creates a support burden immediately as new users can't get going. Having an example at least is nice because we can point there, but having working link is nicer. That said if I recall correctly RN0.60 is about to get rid of link somehow so I everything we know may be about to change

**Comment by MateusAndrade** [comment]
@jgcmarins just test on IOS and Android and it works fine! 🎉🎉🎉

Also, as i discussed with @mikehardy im studying a way to add something similar to react-native-device auto-update on another pr. I also think that i found some minor bugs testing the changes i made.

**Comment by jgcmarins** [comment]
> I also think that i found some minor bugs testing the changes i made.

Cool, can you list any of them?

**Comment by MateusAndrade** [comment]
> Cool, can you list any of them?

Sure! 

- Calling is `isPackageInstalled ` always returns a message saying: Package is Installed. But `isInstalled ` returns false or true depending if the package is installed or not.

- If you run `react-native link`, it seems that the Android link wasn't correct. If doesn't  change the MainApplication, etc. I have one doubt about about that, because on the docs it says that running the link process will do everything automatically. But i can grantee this is working as expected, since i need to change some files by my own.

Did you found any change to be made on the example code? I also added cocoapods for managing the dependencies.

**Comment by jgcmarins** [comment]
did you run `react-native link` or `react-native link react-native-share`?

**Comment by MateusAndrade** [comment]
> react-native link react-native-share

I tested with both. I can test it again later to see if this happen again

**Comment by jgcmarins** [comment]
`react-native link` is wrong
it will try to link every native module

**Comment by MateusAndrade** [comment]
I did a fresh install, linked using ` react-native link react-native-share` and on MainApplication.java the import for `import cl.json.ShareApplication;` are not added, only `import cl.json.RNSharePackage;`. 

This is right?

**Comment by mikehardy** [comment]
I believe that is correct, that one depends on the other stuff and pulls it in. And of course it either runs or not ;-)

**Comment by MateusAndrade** [comment]
BTW maybe i got a misunderstanding. Thanks for clarifying  the things =D

**Comment by mikehardy** [comment]
@MateusAndrade  check this out - clever way to work on a library? https://github.com/johniak/react-native-rewards/blob/master/example/package.json#L8

**Comment by MateusAndrade** [comment]
> @MateusAndrade check this out - clever way to work on a library? https://github.com/johniak/react-native-rewards/blob/master/example/package.json#L8

This looks goods. I think doing this, ir even a .sh would be a good option.Did you testes, How you can work on specific version on ios?

**Comment by mikehardy** [comment]
Not tested - just saw it while reading some other code and made the connection to our previous conversation. I am unable to test below iOS 9.3.5 on real devices (an ancient iPad2,2) or "9.3" on simulator (I didn't install the others because react-native doesn't go below it). I checked stats on version skew in iOS land though and am tranquil about 9+, if you look at minimum supported versions on hardware I think this takes things back nearly 10 years, same as Android 4.1. It's less than 1% of the userbase at this point based on stats for apps I can see and we're not magicians

**Comment by MateusAndrade** [comment]
> Not tested - just saw it while reading some other code and made the connection to our previous conversation. I am unable to test below iOS 9.3.5 on real devices (an ancient iPad2,2) or "9.3" on simulator (I didn't install the others because react-native doesn't go below it). I checked stats on version skew in iOS land though and am tranquil about 9+, if you look at minimum supported versions on hardware I think this takes things back nearly 10 years, same as Android 4.1. It's less than 1% of the userbase at this point based on stats for apps I can see and we're not magicians

I think that old OS's will always be a challenge to any developer. I remember when i used cordova with a AngularJS and have to deal with problems like a break line on Object.assign making the aplicattion crash and other things.

But aiming at IOS >= 9 and Android 4.4 doenst see to be a problem today. Did you looked at react-native-camera or react-native-device? @jgcmarins pointed that there are some points on this projects that would be really to implement on rn-share after releasing a new version on npm.

**Comment by mikehardy** [comment]
Along with @machour, we *are* react-native-device-info, so I have looked yes :-). We have a v2 brewing there where we try to shape up the API and hopefully get CI going (more like react-native-netinfo, which is blazing the trail there). react-native-camera I have only looked at with regard to integration as I use it in a work project. Seems like it's a good example of a large project, and Pod subspecs etc but I have not studied it

**Comment by MateusAndrade** [comment]
> Along with @machour, we _are_ react-native-device-info, so I have looked yes :-). We have a v2 brewing there where we try to shape up the API and hopefully get CI going (more like react-native-netinfo, which is blazing the trail there). react-native-camera I have only looked at with regard to integration as I use it in a work project. Seems like it's a good example of a large project, and Pod subspecs etc but I have not studied it

WOW! I use device-info on some projects. As i have disccussed with you on another PR, i would fins amazing help on the CI/CD. If you need any help, you can count on me. Hahahaha

**Comment by mikehardy** [comment]
That spirit is why I enjoy helping myself and why I pitched in on device-info. team 💪

**Pull request merged**
