### PR TITLE
Instagram stories

### PR DESCRIPTION
**Pull request by loga4**
Hi,

It's an iOS Instagram Stories Share implementation. 

https://developers.facebook.com/docs/instagram/sharing-to-stories

### CODE REVIEW

**Comment by loga4** [comment]
Oh, i'm sorry - i forgot add a squash commit.

Now i write an Android implementaion - maybe do you have some comments, instructions?

**Comment by jgcmarins** [comment]
> Now i write an Android implementaion

Did you implemented for android as well?

**Comment by jgcmarins** [comment]
> maybe do you have some comments, instructions?

I guess I didn't understand. Comments and instructions related to...?

**Comment by jgcmarins** [comment]
I think we're good to merge \o/

**Comment by loga4** [comment]
> Comments and instructions related to...?
to workflow.

Maybe I should have opened the issue first. 
It turns out that i sent a PR from nowhere)

**Comment by jgcmarins** [comment]
Don't worry, we're good.
If you're done with this one, we can merge it.
For android, you can open another PR.

**Comment by loga4** [comment]
iOS done

**Comment by mikehardy** [comment]
Just wanted to say that I still have no idea why this broke the build, but it's a cool feature, it looks like it should work, it sounds like you're using it in production etc., and I'd be happy to help / test a PR that put it back in. But this time checking release mode :-)

**Comment by MateusAndrade** [comment]
> Just wanted to say that I still have no idea why this broke the build, but it's a cool feature, it looks like it should work, it sounds like you're using it in production etc., and I'd be happy to help / test a PR that put it back in. But this time checking release mode :-)

This is definitely  a good addition to this project. @mikehardy what do you think about defining a guide to PRS that have changes on IOS/Android? By ensuring that you need to test on release builds, etc.

**Pull request merged**
