### PR TITLE
feat(social): add social facebook pages manager

### PR DESCRIPTION
**Pull request by emersonlaurentino**

### CODE REVIEW

**Comment by EstebanFuentealba** [comment]
hello, thank you for contributing. Can you add code for IOS?

**Comment by jgcmarins** [comment]
@emersonlaurentino great job.
Could you help us with iOS implementation?

**Comment by emersonlaurentino** [comment]
@jgcmarins  @EstebanFuentealba I cant make this, i dont know much about IOS. Sorry.

**Comment by jgcmarins** [comment]
don't worry, let's keep this one open and see if we find someone that help us

**Comment by emersonlaurentino** [comment]
@jgcmarins done, i added on README!

**Comment by richardkarsten** [comment]
I'm a little bit confused about the iOS part. By trying to understand the standard services of the UIActivityViewController, I found out, its also not possible to send data to pages manager with the genertic solution. Maybe it's not possible until facebook will implement it? 

Seems like I'm not the only one who is not able to find a solution for this:
 
https://stackoverflow.com/questions/46666687/show-facebook-page-manager-in-uiactivityviewcontroller

**Pull request merged**
