### PR TITLE
expose isPackageInstalled 

### PR DESCRIPTION
**Pull request by smokokoi**
This way consumers of this package can also check if a package is installed, which will make this package even more useful.

### CODE REVIEW

**Comment by jgcmarins** [comment]
hello @smokokoi,
thanks for contributing

which issue is this PR related to?

**Comment by smokokoi** [comment]
@jgcmarins hey there!  there's no issue that the PR fixes. It's more like a feature. Instead of asking people to use another package to check if a native app is installed, it can be done via this package, as this functionality is already implemented. 

For example, if I want to share on Instagram and the app is not installed, then I'd like to show an alert with option going to Google Play and download it.

**Comment by jgcmarins** [comment]
> For example, if I want to share on Instagram and the app is not installed, then I'd like to show an alert with option going to Google Play and download it.

Great!
It would be nice to also support iOS.

Another cool improvement is to add those informations on [README](https://github.com/react-native-community/react-native-share/blob/master/README.md)

**Comment by smokokoi** [comment]
You're right. I'll add it. I made sure to include a very easy to understand code in the example.

I didn't add iOS because RN native also supports it with `Linking.canOpenURL`

**Comment by jgcmarins** [comment]
> I didn't add iOS because RN native also supports it with `Linking.canOpenURL`

Great!
Also another good information to add to README

**Comment by smokokoi** [comment]
@jgcmarins - I updated the readme. Please accept the PR.

**Comment by smokokoi** [comment]
cheers :)

**Comment by jgcmarins** [comment]
sure, I will do it as soon as possible
for now, could you use master branch?

**Comment by smokokoi** [comment]
I can't use the master. I'll wait for whenever you release it.

**Comment by jgcmarins** [comment]
I perfectly understand.
This is such a best practices.
You can do like that:
```
"react-native-share": "git+https://github.com/react-native-community/react-native-share.git#03183deb41617a4d145b42bffbea4ca39df0a165"
```
`03183deb41617a4d145b42bffbea4ca39df0a165` is the merge commit, pointing right to your improvements

**Comment by smokokoi** [comment]
@mikehardy + @jgcmarins  - cheers for the advice and I'd totally do it if I were working on my own project. There are other considerations, so I'll just wait for the build. Thank you!

**Pull request merged**
