### PR TITLE
Add linkedin share feature for Android

### PR DESCRIPTION
**Pull request by malaimihai**
I have added linkedin share feature for Android.

### CODE REVIEW

**Comment by MateusAndrade** [comment]
LGTM! I will give a try at this on the weekend. @malaimihai you can verify your commits please?

**Comment by MateusAndrade** [comment]
@malaimihai i think you forget to add the reference to Linkeding on: https://github.com/react-native-community/react-native-share/blob/master/index.js#L168...L176

**Comment by malaimihai** [comment]
> @malaimihai i think you forget to add the reference to Linkedin on: https://github.com/react-native-community/react-native-share/blob/master/index.js#L168...L176

@MateusAndrade I added the reference to Linkedin.

**Comment by jgcmarins** [comment]
ship it \o/

**Comment by MateusAndrade** [comment]
@malaimihai you can update your branch with the master? Then you we can ship it. 🚀

**Comment by malaimihai** [comment]
@MateusAndrade Updated, ready to go

**Comment by MateusAndrade** [comment]
It LGMT. You can sign your commit to merge this? Unfortunately i cant merge PR without signed commits. :cry:

**Comment by MateusAndrade** [comment]
If you have any doubt about setting this you can give a look at this: https://help.github.com/articles/about-gpg/

And this gist to set the key as a global git config: https://gist.github.com/mort3za/ad545d47dd2b54970c102fe39912f305

**Comment by mikehardy** [comment]
@jgcmarins - can we turn off the signing requirement? Even as a person relatively adept at cryptography, I had a hard time setting it up, and I think it poses a barrier to contributions for no real gain since our source is always visible anyway - trust isn't really required at the contributor level, we're all just names with arbitrary avatars anyway ;-)

**Comment by mikehardy** [comment]
I have override-signing-request merge power so I merged this one

**Comment by MateusAndrade** [comment]
> @jgcmarins - can we turn off the signing requirement? Even as a person relatively adept at cryptography, I had a hard time setting it up, and I think it poses a barrier to contributions for no real gain since our source is always visible anyway - trust isn't really required at the contributor level, we're all just names with arbitrary avatars anyway ;-)

I talked with @jgcmarins about that, and i think him dont have the access to disable that. Btw, i commented on the public-hub of react-native-community asking for anyone with admin access to this repo.

**Comment by mikehardy** [comment]
I have admin access to this repo I can turn it off if we agree (I a consensus-based guy ;-) )

**Comment by MateusAndrade** [comment]
> based

WOW! I think this a good idea, since some people dont have idea how set this up. ALso, if we agree we can add @jgcmarins , and me as admin role

**Comment by mikehardy** [comment]
I have removed the requirement for signed requests, @jgcmarins was already an admin, and I granted you admin as well. @jgcmarins can remove that if he disagrees, but I lean towards more permissive / more collaborators so that works for me. If Joao disagrees I apologize in advance !

**Pull request merged**
