### PR TITLE
Issue resolved with android naugat

### PR DESCRIPTION
**Pull request by ravirupareliya**
Issue [185](https://github.com/EstebanFuentealba/react-native-share/issues/185) has been resolved

### CODE REVIEW

**Comment by JonasLaux** [comment]
Is this going to be merged? Currently facing the same issue.

**Comment by ravirupareliya** [comment]
@JonasLaux for me its working perfectly in live project also, i don't know whether they are going to merge it or not, but in my opinion they should do it because now major devices are having naugat and may be in next year oreo also.

**Comment by ifiokjr** [comment]
Would be useful for a project that we're running. For now, we'll need to use your fork @ravirupareliya - Thanks!

**Comment by sibelius** [comment]
@ygorbarboza this PR makes sense for you?

can we merge it?

**Comment by ygorbarboza** [comment]
it makes sense, but not everybody gonna use the same `${applicationId}.provider` as his authorites and provider_paths.xml also can be different on each app.

**Comment by sibelius** [comment]
@ravirupareliya tks for the work on this PR

can you check if this PR https://github.com/EstebanFuentealba/react-native-share/pull/181 also solves your issue?

you can test using master

**Comment by ravirupareliya** [comment]
@ygorbarboza Don't you think `${applicationId}.provider` will take package name of current application which is using this library, so i guess that will be unique in all applications.

**Comment by ravirupareliya** [comment]
@sibelius Surely i would love to help but currently i am not in a position to test it. Sorry for that, but whatever things i have pushed is working in my all applications which are live on playstore.

**Comment by ygorbarboza** [comment]
@ravirupareliya the problem is that not all react native app started as a react native app. Most of them have RN as part of the app, and already have a authority set on manifest

**Comment by jgcmarins** [comment]
@ravirupareliya looks good!
Could you please resolve conflicts?

**Comment by ravirupareliya** [comment]
@jgcmarins Can you please look into it again? I have resolve this conflict from mobile, so not sure whether i have done anything wrong or not.

**Comment by jgcmarins** [comment]
@ravirupareliya it has some indentation problems, but looks good.
Thanks \o/

**Comment by kkbhav** [comment]
No activity. Closing this PR!

**Pull request closed without merging**
