### PR TITLE
Revert "Instagram stories (#449)" / Fix iOS release build in 1.2.0

### PR DESCRIPTION
**Pull request by mikehardy**
This reverts commit e4d8ebdc1cdcf8bfec0316b205c87fade7e9f232.

As mentioned in #504 there is a link failure in release mode for iOS, and it appears to be caused by #449 

This reverts #449 until it can be repaired and iOS release builds work while it is integrated

Worth noting that #449 looks fine - it is a good feature and I am not sure what went wrong in the XCode project change - but if fails to archive in release mode at the moment

Also thankfully even though we haven't configured CI yet #290 we have astute community members that report things clearly and quickly

### CODE REVIEW

**Comment by mikehardy** [comment]
In it's original form my revert was incomplete but I just hopped off a plane and had time to test it more fully and now it appears complete

**Comment by mikehardy** [comment]
Curious what the status is on this? There's an independent report that instagram stories is the likely cause, as reverting to the commit prior archives correctly. I still see 1.2.0 on npmjs.com and this PR and the related 1.2.0 link failure are both open. So it is my current understanding that our most recent release is still unusable in production, right? Do we have a plan to merge this and do a 1.2.1 that archives? Or did I miss a different PR fix go in?

**Comment by jgcmarins** [comment]
@mikehardy we haven't found the solution yet.
If reverting Instagram support solves 1.2.0, we can merge it and release 1.2.1.

**Comment by mikehardy** [comment]
The PR reverting Instagram stories fixes ios archive error on  1.2.0, yes

**Comment by MateusAndrade** [comment]
Since we cant find whats happening on IOS production builds using 1.2.0. i think publishing a version 1.2.1 removing the Instagram Stories is a good begining.

Then, fixing the Instagram Stories we can send a 1.2.2. We just need to adjust the docs about this change.

**Comment by mikehardy** [comment]
Confirming 1.2.1 archives in release mode correctly in testing. whew!

**Comment by jgcmarins** [comment]
This is awesome!
Thank you @mikehardy \o/

**Pull request merged**
