### PR TITLE
Add "email" field to share dialog + Handling null reference exception

### PR DESCRIPTION
**Pull request by meni-cherbakovsky**
Support sending an email to a predefined email address. Documentation
updated as well.

### CODE REVIEW

**Comment by meni-cherbakovsky** [comment]
@EstebanFuentealba, did you take a look at the PR?
Thanks :)

**Comment by gauravmnit07** [comment]
@EstebanFuentealba  is there any update on this? Are we going to support this in library?

**Comment by abarisic86** [comment]
hi @meni-cherbakovsky, do you think this PR is still useful? did you try developing the same feature on iOS? can you chekout the conflict and fix it? fyi @jgcmarins

**Comment by jgcmarins** [comment]
thanks @abarisic86

**Comment by enieber** [comment]
the function is reusable to close the [PR #138](https://github.com/react-native-community/react-native-share/pull/138)?

**Comment by enieber** [comment]
this PR need resolve conflict

**Comment by meni-cherbakovsky** [comment]
@abarisic86, conflicts resolved. This PR is for android only. I can try to apply it on iOS as well (in a separate PR)

**Comment by meni-cherbakovsky** [comment]
BTW, I see that @enieber has a solution for iOS

**Comment by MateusAndrade** [comment]
@meni-cherbakovsky do you think this PR still useful? You can give a look at the last version of react-native-share, and update your fork? 😄

**Pull request closed without merging**
