### PR TITLE
Fix singleShare for social Media

### PR DESCRIPTION
**Pull request by ddereszewski**
We discover an issue with SingleShare on Android. Details explained here #344

### CODE REVIEW

**Comment by ddereszewski** [comment]
Please allow some additional testing before merging.

**Comment by jgcmarins** [comment]
@ddereszewski what do you suggest?

**Comment by ddereszewski** [comment]
The original commit didn't work on Android 6. Now It's good go!

**Comment by ddereszewski** [comment]
We don't use ReactNativeShare on IOS as we use direct Linking, so I can't tell from experience. I looked into the IOS implementation and it's similar to what we have on RN. 

Here the issue is android specific, I wouldn't expect problems on IOS, but I'm happy to help in future if something occurs and have a bit of time.

**Pull request merged**
