### PR TITLE
Send email to predefined email address

### PR DESCRIPTION
**Pull request by valioz**
# Overview
Support sending an email to a predefined email address.
It is based on PR #138 and PR #67, fixes issue #487.

### CODE REVIEW

**Comment by MateusAndrade** [comment]
@valioz thanks for helping us with that! 

On which applications did you tested your changes? (Outlook, Gmail, etc )

**Comment by valioz** [comment]
I have tested it on a Gmail (Android)

**Comment by MateusAndrade** [comment]
This looks good to me. You can please update your base branch with the master version @valioz ?

**Comment by MateusAndrade** [comment]
HI @valioz , you can updated your base branch with the last changes on master? I tested this on both Android/IOS and it looks fine.

**Comment by MateusAndrade** [comment]
@valioz thanks! 🎉

**Comment by fedu44** [comment]
On iOS with the default email app (mail), the TO field is not working correctly, it's not being fill at all

**Pull request merged**
