### PR TITLE
Remove unnecessary tools replace on build gradle

### PR DESCRIPTION
**Pull request by luancurti**
# Overview
Remove tools replace that was causing warnings

# Test Plan
Run build without problems

### CODE REVIEW

**Comment by luancurti** [comment]
Before this fix the warnings in build

Screen Shot 2019-10-03 at 23 43 21

**Comment by mikehardy** [comment]
If I understand correctly this is might be related to the change where rnshare added a default provider etc? Could be considered a remnant in that case and good to clean out

**Comment by MateusAndrade** [comment]
@luancurti did you tested this on the release and debug mode?

**Comment by luancurti** [comment]
@MateusAndrade yes, before I made this PR I referenced my repository and installed in my app, running in debug and release mode, inside this project running `./gradlew assembleRelease` app build successfull

**Comment by MateusAndrade** [comment]
Thanks @luancurti ! 🎉

**Pull request merged**
